import type { BookChapter } from './types';

/**
 * The Paramedic Book — prose reference chapters.
 *
 * Scope note: this is a *training* reference sized to ResponderIQ, not a
 * protocol set. Every clinical statement here is the widely-taught general
 * case; the trainee's agency protocols and on-line medical direction always
 * govern the real call. That caveat is rendered once, prominently, by the UI
 * (see PROTOCOL_DISCLAIMER) rather than repeated on every card.
 */

export const PROTOCOL_DISCLAIMER =
  'Training reference only. Your agency protocols, scope of practice, and on-line medical direction govern every real patient contact — where they differ from this book, they win.';

export const BOOK_CHAPTERS: readonly BookChapter[] = [
  {
    id: 'scene',
    title: 'Scene size-up and safety',
    purpose:
      'Everything you decide before you touch the patient. A scene you did not read is a scene that gets to surprise you later.',
    entries: [
      {
        id: 'windshield-survey',
        title: 'Windshield survey',
        summary:
          'The look you take from inside the unit, before the doors open, while you still have the option to leave.',
        points: [
          'Read the whole block, not the address: traffic, crowd, dogs, lighting, exits, where you would back out to.',
          'Note where you park. Uphill and upwind of a hazard; leave yourself an escape lane rather than boxing in behind the engine.',
          'Count the patients out loud. The patient count you call in is what sizes the response — correct it early rather than quietly.',
          'Identify the entry and the exit you would carry a patient out through. On BLS-01 that decision is the call.',
          'If any part of the scene reads unsafe, stage and request law enforcement. Staging is a decision, not a delay.',
        ],
        keywords: ['size-up', 'sizeup', 'arrival', 'approach', 'park', 'positioning'],
      },
      {
        id: 'scene-safety',
        title: 'Scene safety and staging',
        summary: 'Your safety, your partner’s, the bystanders’, the patient’s — in that order, every time.',
        points: [
          'Order of protection: you, your crew, bystanders, then the patient. Reversing it makes two patients out of one.',
          'Stage for reported violence, weapons, active assailants, unsecured animals, hazmat, or an unstable structure — and say on the radio that you are staging and where.',
          'You do not enter until law enforcement declares the scene secure. "Secured" from dispatch relay is not the same as secured by the officer on scene.',
          'Re-evaluate continuously. A scene that was safe on entry can turn while you are packaging.',
          'Any crew member can call for retreat. Nobody has to justify it in the moment.',
        ],
        keywords: ['staging', 'police', 'law enforcement', 'violence', 'retreat', 'danger'],
      },
      {
        id: 'ppe-bsi',
        title: 'PPE and body substance isolation',
        summary: 'Chosen from the mechanism and the complaint, before contact — not after you see blood.',
        points: [
          'Gloves for every patient contact, without exception.',
          'Eye protection and mask for airway management, suctioning, active bleeding, or any coughing patient.',
          'Gown for major trauma, childbirth, or heavy contamination.',
          'N95 or better for suspected airborne infection; mask the patient too, if they tolerate it.',
          'Escalate for the mechanism: helmet, high-visibility vest, and turnout gear on the roadway; ballistic protection where your agency issues it and the scene calls for it.',
        ],
        keywords: ['gloves', 'mask', 'gown', 'n95', 'bsi', 'protection', 'ballistic', 'vest'],
      },
      {
        id: 'mci-triage',
        title: 'START triage',
        summary: 'When patients outnumber hands, sorting fast beats treating one well.',
        points: [
          'Walking wounded to a designated area first — that is the GREEN group, and it clears the field.',
          'Respirations absent: open the airway. Still absent, tag BLACK (expectant). Breathing after positioning, tag RED (immediate).',
          'Respirations over 30/min: RED.',
          'Perfusion — radial pulse absent or capillary refill over 2 seconds: RED. Control major bleeding as you pass.',
          'Mental status — cannot follow simple commands: RED. Follows commands: YELLOW (delayed).',
          'The only treatments during triage are opening an airway and stopping major hemorrhage. Nothing else. You come back.',
        ],
        keywords: ['mci', 'mass casualty', 'start', 'triage', 'red', 'yellow', 'green', 'black', 'immediate', 'delayed'],
      },
    ],
  },
  {
    id: 'assessment',
    title: 'Patient assessment',
    purpose:
      'The order you find things in. The sequence exists so that what kills first gets found first — it is not a checklist to recite.',
    entries: [
      {
        id: 'primary-assessment',
        title: 'Primary assessment — XABCDE',
        summary: 'Find and fix immediate life threats before you go looking for a diagnosis.',
        points: [
          'X — Exsanguinating hemorrhage. Catastrophic external bleeding is controlled before anything else: direct pressure, then tourniquet high and tight.',
          'A — Airway with spinal motion restriction where the mechanism warrants it. Open it, keep it, and suction what you cannot keep out.',
          'B — Breathing. Rate, depth, effort, symmetry, sounds. Treat what you find now: oxygen, ventilate, decompress.',
          'C — Circulation. Central and peripheral pulses, skin color, temperature, moisture, capillary refill, obvious bleeding.',
          'D — Disability. AVPU or GCS, pupils, gross motor and sensation in all four, and a blood glucose on anyone altered.',
          'E — Expose to examine, then cover to preserve heat. Hypothermia kills trauma patients that the injury did not.',
          'End the primary with a transport decision, out loud: immediate, or continue on scene.',
        ],
        keywords: ['abc', 'xabcde', 'primary survey', 'life threat', 'initial assessment'],
      },
      {
        id: 'avpu-gcs',
        title: 'AVPU and Glasgow Coma Scale',
        summary: 'Two ways to say the same thing at different resolutions. Trend matters more than either number.',
        points: [
          'AVPU: Alert / responds to Verbal / responds to Painful stimulus / Unresponsive. Fast, and enough for the primary.',
          'GCS eye opening (4): spontaneous 4, to speech 3, to pain 2, none 1.',
          'GCS verbal (5): oriented 5, confused 4, inappropriate words 3, incomprehensible sounds 2, none 1.',
          'GCS motor (6): obeys commands 6, localizes pain 5, withdraws 4, abnormal flexion 3, abnormal extension 2, none 1.',
          'Minimum 3, maximum 15. Report the components, not just the total — "E3 V4 M5" says far more than "12".',
          'A GCS of 8 or less, or a two-point drop, is the classic trigger to protect the airway and re-evaluate transport.',
        ],
        keywords: ['gcs', 'avpu', 'mental status', 'loc', 'consciousness', 'glasgow'],
      },
      {
        id: 'sample-opqrst',
        title: 'SAMPLE and OPQRST',
        summary: 'The history. Most of your diagnosis lives here, not in the exam.',
        points: [
          'SAMPLE — Signs and symptoms; Allergies; Medications; Past medical history; Last oral intake; Events leading up.',
          'OPQRST — Onset; Provocation and palliation; Quality; Region and radiation; Severity (0–10); Time course.',
          'Ask the patient before you ask the family. Then ask the family what the patient did not say.',
          'Medication bottles are history you can read: bring them, or photograph the labels.',
          '"Events leading up" is where mechanism hides. Did they fall because they fell, or did they fall because they syncopized?',
        ],
        keywords: ['history', 'sample', 'opqrst', 'interview', 'chief complaint', 'hpi'],
      },
      {
        id: 'secondary-assessment',
        title: 'Secondary assessment',
        summary: 'Head-to-toe, or focused on the complaint — the choice is the mechanism’s to make, not yours.',
        points: [
          'Significant mechanism or altered patient: full head-to-toe, rapidly. Isolated complaint on an alert patient: focused exam.',
          'DCAP-BTLS at each region — Deformity, Contusion, Abrasion, Puncture; Burn, Tenderness, Laceration, Swelling.',
          'Look, then feel, then listen — and expose the region you are examining. You do not find a flail segment through a coat.',
          'Posterior gets examined too. Log-roll or lift, but do not skip the back because it is inconvenient.',
          'Document what you found AND what you deliberately looked for and did not find. A pertinent negative is a finding.',
        ],
        keywords: ['secondary survey', 'head to toe', 'dcap', 'btls', 'physical exam', 'focused exam'],
      },
      {
        id: 'reassessment',
        title: 'Reassessment',
        summary: 'The single most-skipped skill in EMS, and the one that catches the deterioration.',
        points: [
          'Unstable patient: every 5 minutes. Stable patient: every 15.',
          'Repeat the primary, repeat the vitals, and recheck every intervention you performed — oxygen still flowing, splint still distal-pulse-positive, IV still running.',
          'One set of vitals is a data point. Two is a trend, and only the trend tells you which way the patient is going.',
          'Reassess after every intervention and after every move. Moving a patient is an intervention.',
          'Any change in mental status restarts the primary assessment from A.',
        ],
        keywords: ['ongoing assessment', 'trending', 'repeat vitals', 'monitor'],
      },
    ],
  },
  {
    id: 'airway',
    title: 'Airway and ventilation',
    purpose: 'An airway you have and are keeping. Everything downstream depends on this chapter being finished.',
    entries: [
      {
        id: 'airway-basics',
        title: 'Positioning and basic adjuncts',
        summary: 'Do the basic thing well before you reach for the advanced thing.',
        points: [
          'Head-tilt chin-lift for the medical patient; jaw thrust where you are holding spinal motion restriction.',
          'Suction what you can see, under direct vision, for no more than about 10 seconds in an adult — and pre-oxygenate around it.',
          'OPA: sized corner of the mouth to angle of the jaw. Only in a patient with no gag reflex.',
          'NPA: sized nostril to earlobe, lubricated, bevel toward the septum. Tolerated by patients who will not take an OPA. Use caution with suspected midface or basilar skull fracture.',
          'Ear-to-sternal-notch positioning improves nearly every airway — including the obese and pregnant patient, who need ramping.',
        ],
        keywords: ['opa', 'npa', 'oropharyngeal', 'nasopharyngeal', 'suction', 'jaw thrust', 'head tilt'],
      },
      {
        id: 'oxygen-delivery',
        title: 'Oxygen delivery devices',
        summary: 'Match the device to the deficit. More oxygen is not automatically better.',
        points: [
          'Nasal cannula: 1–6 L/min, roughly 24–44% oxygen. Comfortable, and the right first step for mild hypoxia.',
          'Simple mask: 6–10 L/min, roughly 35–60%.',
          'Non-rebreather: 10–15 L/min, roughly 60–90%. Inflate the reservoir before you put it on the face.',
          'Bag-valve mask with reservoir at 15 L/min approaches 100% — and is the device for inadequate ventilation, not merely low saturation.',
          'Target a saturation of about 94–99% for most patients. Titrate down once you get there; routine high-flow oxygen in the adequately-saturated patient is not benign.',
          'Suspected COPD with chronic retention: titrate to roughly 88–92% and watch the work of breathing, not just the number.',
        ],
        keywords: ['spo2', 'oxygen', 'nrb', 'non rebreather', 'nasal cannula', 'saturation', 'copd', 'titrate'],
      },
      {
        id: 'bvm-ventilation',
        title: 'Bag-valve-mask ventilation',
        summary: 'The highest-yield airway skill there is, and the easiest one to do badly.',
        points: [
          'Two-person technique whenever a second pair of hands exists: one seals with a two-handed C-E or thenar grip, one squeezes.',
          'Adult rate about 10–12 breaths/min with a pulse; roughly one breath every 6 seconds. Ventilate only until the chest rises.',
          'Too fast and too much are the two classic errors: both raise intrathoracic pressure, drop venous return, and inflate the stomach.',
          'With an advanced airway in cardiac arrest: about 10 breaths/min, continuous compressions, no pauses to ventilate.',
          'If the chest does not rise: reposition, re-seal, place an adjunct, check for obstruction — in that order.',
        ],
        keywords: ['bvm', 'bagging', 'ventilate', 'bag valve mask', 'rate', 'gastric insufflation'],
      },
      {
        id: 'advanced-airway',
        title: 'Advanced airway and confirmation',
        summary: 'Placement is half the skill. Proving and keeping the placement is the other half.',
        points: [
          'Supraglottic airways are fast, high-success rescue devices and are an entirely acceptable primary airway in arrest.',
          'Confirm every advanced airway with waveform capnography — it is the standard, not a nice-to-have. Bilateral sounds plus absent epigastric sounds plus chest rise support it; capnography settles it.',
          'Re-confirm placement after every patient move: the stair chair, the cot, and the loading are all tube-dislodging events.',
          'Secure the device, mark the depth, and document both the depth and the confirmation method.',
          'DOPE for the sudden deterioration of an intubated patient: Displacement, Obstruction, Pneumothorax, Equipment failure.',
        ],
        keywords: ['intubation', 'ett', 'supraglottic', 'igel', 'king', 'lma', 'dope', 'tube'],
      },
      {
        id: 'capnography',
        title: 'Waveform capnography',
        summary: 'The closest thing prehospital care has to a real-time perfusion monitor.',
        points: [
          'Normal end-tidal CO2 is roughly 35–45 mmHg with a squared-off waveform.',
          'A sudden drop to near zero means the tube is out, the circuit is disconnected, or the patient has arrested. Look at the patient first.',
          'A gradual fall suggests falling cardiac output or hyperventilation; a gradual rise suggests hypoventilation or rising output.',
          'In CPR, an ETCO2 under about 10 mmHg points at compression quality. Fix the compressions before you blame the patient.',
          'An abrupt jump into the normal range during CPR is a strong sign of return of spontaneous circulation — confirm with a pulse check at the next rhythm check.',
          'A sloped, "shark-fin" waveform is bronchospasm — asthma or COPD — regardless of the number on the display.',
        ],
        keywords: ['etco2', 'end tidal', 'capnography', 'waveform', 'rosc', 'shark fin'],
      },
    ],
  },
  {
    id: 'cardiac',
    title: 'Cardiac and 12-lead',
    purpose: 'Rhythm, perfusion, and the decision each combination forces.',
    entries: [
      {
        id: 'cpr-quality',
        title: 'High-quality CPR',
        summary: 'The intervention with the best evidence behind it, and it is entirely mechanical.',
        points: [
          'Adult depth at least 2 inches (5 cm) and not more than about 2.4 inches (6 cm), at 100–120 compressions per minute.',
          'Full recoil every time. Leaning on the chest between compressions is a common and costly error.',
          'Minimize interruptions — aim for a chest compression fraction above 80%. Pre-charge the defibrillator before the rhythm check.',
          'Rotate compressors every 2 minutes, at the rhythm check, so the swap costs nothing.',
          'Compression-to-ventilation 30:2 without an advanced airway; continuous compressions with about 10 breaths/min once one is in.',
          'Pediatric depth is about one third of the chest’s anterior-posterior diameter; 30:2 single-rescuer, 15:2 with two rescuers.',
        ],
        keywords: ['cpr', 'compressions', 'arrest', 'ccf', 'depth', 'rate', 'recoil'],
      },
      {
        id: 'arrest-rhythms',
        title: 'Cardiac arrest rhythms',
        summary: 'Two shockable, two not. The branch point of every arrest algorithm.',
        points: [
          'Shockable: ventricular fibrillation and pulseless ventricular tachycardia. Defibrillate immediately and resume compressions without a pulse check.',
          'Non-shockable: pulseless electrical activity and asystole. Compressions, epinephrine, and a relentless hunt for the cause.',
          'Confirm asystole in a second lead and check leads and gain before you accept it — fine VF masquerades as a flat line.',
          'Epinephrine 1 mg IV/IO every 3–5 minutes throughout the arrest.',
          'Antiarrhythmic for refractory VF/pVT: amiodarone 300 mg IV/IO, then 150 mg; or lidocaine per your protocol.',
          'The Hs and Ts are the whole of PEA management: hypovolemia, hypoxia, hydrogen ion (acidosis), hypo/hyperkalemia, hypothermia; tension pneumothorax, tamponade, toxins, thrombosis (coronary), thrombosis (pulmonary).',
        ],
        keywords: ['vf', 'vfib', 'vtach', 'pea', 'asystole', 'acls', 'defibrillation', 'hs and ts', 'shockable'],
      },
      {
        id: 'brady-tachy',
        title: 'Bradycardia and tachycardia with a pulse',
        summary: 'One question decides the pathway: is the patient unstable because of the rate?',
        points: [
          'Instability means hypotension, altered mental status, signs of shock, ischemic chest pain, or acute heart failure — caused by the rhythm.',
          'Symptomatic bradycardia: atropine 1 mg IV every 3–5 minutes to a maximum of 3 mg; then transcutaneous pacing, or a chronotropic infusion.',
          'Pace with sedation and analgesia where the patient is awake enough to feel it, and confirm mechanical capture with a pulse — not just electrical capture on the screen.',
          'Stable narrow-complex regular tachycardia: vagal maneuvers, then adenosine 6 mg rapid IV push with a flush, then 12 mg.',
          'Unstable tachycardia of any width: synchronized cardioversion. Sedate if the patient’s condition and time allow.',
          'Wide-complex tachycardia in an adult is ventricular until proven otherwise. Treat it that way.',
        ],
        keywords: ['bradycardia', 'tachycardia', 'svt', 'pacing', 'cardioversion', 'adenosine', 'atropine', 'unstable'],
      },
      {
        id: 'twelve-lead',
        title: '12-lead acquisition and STEMI',
        summary: 'A prehospital 12-lead moves the reperfusion clock. Acquire it early and transmit it.',
        points: [
          'Acquire within about 10 minutes of patient contact for any chest pain, and for anyone with an anginal equivalent: dyspnea, syncope, epigastric pain, or unexplained diaphoresis.',
          'STEMI criteria: ST elevation of at least 1 mm in two contiguous limb leads, or at least 2 mm in two contiguous precordial leads (about 1.5 mm in V2–V3 for women).',
          'Territories — inferior: II, III, aVF. Lateral: I, aVL, V5, V6. Anterior/septal: V1–V4. Posterior: reciprocal depression in V1–V3.',
          'Inferior STEMI: get a right-sided 12-lead (V4R). Right ventricular infarct is preload-dependent — nitroglycerin can drop the pressure through the floor.',
          'Transmit or announce a STEMI alert early; the receiving hospital activating the cath lab from your ECG is the point of acquiring it.',
          'Reduce artifact before you blame the patient: skin prep, correct lead placement, and a still patient. Repeat serial 12-leads if the pain changes.',
        ],
        keywords: ['ecg', 'ekg', '12 lead', 'stemi', 'st elevation', 'mi', 'infarct', 'chest pain', 'v4r'],
      },
    ],
  },
  {
    id: 'trauma',
    title: 'Trauma',
    purpose: 'Time-critical, mechanically driven, and mostly about what you do NOT stop to do.',
    entries: [
      {
        id: 'hemorrhage-control',
        title: 'Hemorrhage control',
        summary: 'The most survivable cause of preventable trauma death, and it is fixable with your hands.',
        points: [
          'Direct pressure first, hard and uninterrupted, with a gloved hand on the bleeding point rather than on a stack of gauze.',
          'Tourniquet for life-threatening extremity bleeding that pressure does not control — high and tight, tightened until the bleeding stops and the distal pulse is gone.',
          'Write the time of application. Do not loosen it in the field to "check".',
          'Junctional and truncal bleeding: wound packing with hemostatic gauze plus sustained direct pressure.',
          'A tourniquet hurts. Tell the patient why it is staying on and treat the pain if your protocol allows it.',
        ],
        keywords: ['bleeding', 'tourniquet', 'hemorrhage', 'wound packing', 'hemostatic', 'cat'],
      },
      {
        id: 'shock',
        title: 'Shock recognition',
        summary: 'Perfusion failure. Blood pressure is the last thing to go, so stop waiting for it.',
        points: [
          'Early compensated signs: anxiety and restlessness, tachycardia, narrowing pulse pressure, pale cool clammy skin, delayed capillary refill.',
          'Decompensated: hypotension, altered mental status, weak or absent peripheral pulses, bradycardia as a terminal sign.',
          'Hypovolemic — bleeding or fluid loss. Hemorrhage control first, then permissive fluids; the fix for bleeding is not saline.',
          'Distributive — septic, anaphylactic, neurogenic. Warm and vasodilated early rather than cool and clamped down.',
          'Cardiogenic — pump failure. Fluid can make it worse; look for pulmonary edema before you open the line up.',
          'Obstructive — tension pneumothorax, tamponade, pulmonary embolism. The fix is the obstruction, not the volume.',
          'Keep them warm. Hypothermia, acidosis, and coagulopathy are the trauma triad, and the blanket is the part you control.',
        ],
        keywords: ['shock', 'hypoperfusion', 'hypovolemic', 'cardiogenic', 'septic', 'neurogenic', 'compensated'],
      },
      {
        id: 'spinal-motion',
        title: 'Spinal motion restriction',
        summary: 'Modern practice restricts motion; it does not automatically strap everyone to a board.',
        points: [
          'Indications turn on mechanism plus findings: midline spinal tenderness, focal neurological deficit, altered mental status, intoxication, or a distracting injury.',
          'A reliable, alert patient with no midline tenderness, no deficit and no distracting injury generally does not need restriction.',
          'Manual in-line stabilization, a properly-sized collar, and a padded cot achieve motion restriction; a long board is an extrication tool, not a transport surface.',
          'Keep the head in neutral alignment — pad behind the head of an adult, and behind the shoulders of a small child, whose occiput is large.',
          'Document neurological function in all four extremities before and after every move.',
        ],
        keywords: ['c-spine', 'cspine', 'collar', 'backboard', 'long board', 'smr', 'immobilization', 'spine'],
      },
      {
        id: 'chest-trauma',
        title: 'Chest trauma',
        summary: 'A small number of injuries in this box kill in minutes. Find them in the primary.',
        points: [
          'Tension pneumothorax: worsening dyspnea, absent unilateral breath sounds, hypotension, distended neck veins, late tracheal deviation. Decompress — do not wait for the deviation.',
          'Open ("sucking") chest wound: vented occlusive dressing, and reassess for tension after you seal it.',
          'Flail segment: paradoxical movement over two or more ribs broken in two or more places. The killer is the underlying pulmonary contusion — support ventilation.',
          'Cardiac tamponade: hypotension, muffled heart tones, distended neck veins. Prehospital care is rapid transport to a surgeon.',
          'Massive hemothorax presents as shock with absent sounds and a dull percussion note — the volume is in the chest.',
        ],
        keywords: ['pneumothorax', 'tension', 'flail chest', 'hemothorax', 'tamponade', 'decompression', 'sucking chest wound'],
      },
      {
        id: 'burns',
        title: 'Burns',
        summary: 'Stop the burning, then treat the burn like the systemic injury it is.',
        points: [
          'Stop the burning process, remove jewelry and non-adherent clothing, and then keep the patient warm — cooling a large burn causes hypothermia.',
          'Rule of Nines in an adult: head 9%, each arm 9%, each leg 18%, anterior trunk 18%, posterior trunk 18%, genitalia 1%.',
          'The patient’s own palm including fingers is roughly 1% — the practical tool for scattered burns.',
          'Airway burn signs: singed nasal hair, soot in the mouth or sputum, hoarseness, stridor, facial burns, or an enclosed-space fire. The airway closes progressively — act early.',
          'Suspect carbon monoxide or cyanide exposure in enclosed-space fires. Pulse oximetry reads falsely normal in carbon monoxide poisoning.',
          'Cover with a clean dry dressing. Wet dressings on large burns are a hypothermia route.',
        ],
        keywords: ['burn', 'rule of nines', 'tbsa', 'inhalation', 'carbon monoxide', 'cyanide', 'thermal'],
      },
    ],
  },
  {
    id: 'medical',
    title: 'Medical emergencies',
    purpose: 'The recurring medical presentations, and the finding that changes the plan in each.',
    entries: [
      {
        id: 'stroke',
        title: 'Stroke',
        summary: 'A time-critical medical emergency. Your job is recognition, last-known-well, and the right destination.',
        points: [
          'Cincinnati scale: facial droop, arm drift, abnormal speech. Any one positive raises the probability substantially.',
          'Establish the last known well time — not the time symptoms were found. That number decides eligibility for treatment; get it from a witness and get their phone number.',
          'Check a blood glucose on every suspected stroke. Hypoglycemia mimics stroke and is fixable in seconds.',
          'Do not routinely lower blood pressure in the field; the hospital does that with the scan in hand.',
          'Transport to a stroke-capable center and pre-alert. Bring the witness or their number with you.',
        ],
        keywords: ['cva', 'stroke', 'cincinnati', 'lkw', 'last known well', 'facial droop', 'fast'],
      },
      {
        id: 'seizure',
        title: 'Seizure',
        summary: 'Most self-terminate. The ones that do not are a true emergency.',
        points: [
          'During: protect the head, do not restrain, put nothing in the mouth, time it, and note what moved and in what order.',
          'After: position for airway protection, suction, oxygen, and check a glucose. Expect a postictal period and re-orient gently.',
          'Status epilepticus — a seizure of more than about 5 minutes, or seizures without recovery in between — is treated now with a benzodiazepine.',
          'Look for the cause: hypoglycemia, hypoxia, head injury, fever in a child, eclampsia in pregnancy, toxins, or withdrawal.',
          'Eclampsia in a pregnant or recently-pregnant patient is treated with magnesium sulfate.',
        ],
        keywords: ['seizure', 'status epilepticus', 'postictal', 'convulsion', 'eclampsia', 'benzodiazepine'],
      },
      {
        id: 'diabetic',
        title: 'Diabetic emergencies',
        summary: 'Check a glucose on everyone altered. It is the cheapest diagnosis you will ever make.',
        points: [
          'Hypoglycemia is typically under about 70 mg/dL and presents fast: diaphoresis, tachycardia, confusion, combativeness, seizure.',
          'Awake and able to protect their airway: oral glucose. Unable: dextrose IV, or glucagon IM where there is no line.',
          'Hyperglycemia and diabetic ketoacidosis come on over hours to days: polyuria, polydipsia, Kussmaul respirations, fruity breath, dehydration.',
          'DKA management in the field is fluid and transport. Insulin is a hospital decision.',
          'Recheck the glucose after treatment, and again before you sign off any refusal — hypoglycemia recurs, especially on long-acting agents.',
        ],
        keywords: ['hypoglycemia', 'hyperglycemia', 'dka', 'glucose', 'sugar', 'insulin', 'dextrose', 'glucagon'],
      },
      {
        id: 'respiratory-distress',
        title: 'Respiratory distress',
        summary: 'Work of breathing tells you more than any number on the monitor.',
        points: [
          'Asthma and COPD: wheeze, prolonged expiration, accessory muscle use. Bronchodilators, and CPAP where the patient tolerates it.',
          'A silent chest in an asthmatic is not improvement — it is a patient who has stopped moving air.',
          'Acute pulmonary edema: crackles, orthopnea, frothy sputum, hypertension. CPAP plus nitroglycerin is the standard prehospital pairing.',
          'Pulmonary embolism: sudden dyspnea with clear lungs, pleuritic pain, tachycardia, and risk factors. Often a diagnosis of suspicion.',
          'Anaphylaxis: intramuscular epinephrine early, into the lateral thigh. Do not wait for hypotension when the airway is involved.',
          'CPAP contraindications include apnea, hypotension, vomiting, an inability to protect the airway, or a suspected pneumothorax.',
        ],
        keywords: ['asthma', 'copd', 'wheeze', 'cpap', 'pulmonary edema', 'chf', 'pe', 'anaphylaxis', 'dyspnea', 'sob'],
      },
      {
        id: 'overdose',
        title: 'Overdose and poisoning',
        summary: 'Treat the patient and the airway, not the substance you were told about.',
        points: [
          'Opioid toxidrome: respiratory depression, pinpoint pupils, depressed consciousness. Ventilate first — naloxone second.',
          'Titrate naloxone to adequate respirations, not to a fully awake patient. A patient who wakes up agitated and leaves is a worse outcome than a patient who breathes.',
          'Sympathomimetic toxidrome: tachycardia, hypertension, hyperthermia, dilated pupils, agitation. Cooling and benzodiazepines, not physical restraint alone.',
          'Anticholinergic: hot, dry, red, blind, mad — flushed dry skin, dilated pupils, delirium, urinary retention.',
          'Cholinergic (SLUDGE): salivation, lacrimation, urination, defecation, GI upset, emesis, with bronchorrhea. Atropine, and consider your own decontamination.',
          'Bring the bottles, the paraphernalia, and the substance name. Call poison control early where your system uses it.',
        ],
        keywords: ['overdose', 'od', 'opioid', 'naloxone', 'narcan', 'toxidrome', 'poisoning', 'sludge', 'stimulant'],
      },
    ],
  },
  {
    id: 'moving',
    title: 'Lifting, moving and extrication',
    purpose:
      'The chapter that decides ResponderIQ’s first scenario: getting a patient out of a building is a plan, not a lift.',
    entries: [
      {
        id: 'body-mechanics',
        title: 'Body mechanics',
        summary: 'Careers end here more often than they end on a scene.',
        points: [
          'Lift with the legs, keep the load close, keep your back straight, and never twist while loaded.',
          'Know the weight before you commit to it, and say the number out loud to your crew.',
          'One person calls the lift, and everyone lifts on that count. Two people counting is how someone gets dropped.',
          'Ask for help early. Requesting a lift assist costs minutes; a dropped patient or an injured back costs far more.',
          'Push rather than pull where you have the choice, and work at waist level.',
        ],
        keywords: ['lifting', 'body mechanics', 'back injury', 'lift assist', 'weight'],
      },
      {
        id: 'moving-devices',
        title: 'Choosing the moving device',
        summary: 'The route out of the building picks the device — not the other way round.',
        points: [
          'Stair chair: the tool for a conscious patient down a narrow staircase. It is not for a patient who cannot sit or who needs their spine kept in line.',
          'Scoop stretcher: splits and reassembles around a patient in a confined space, with minimal rolling.',
          'Long board: an extrication device for moving a patient out, and increasingly not the surface they get transported on.',
          'Flexible stretcher or reeves: the answer to tight turns, narrow hallways and staircases with a landing.',
          'Walk the route before you package. Measure the turn at the bottom of the stairs; that is where a plan actually fails.',
        ],
        keywords: ['stair chair', 'scoop', 'backboard', 'reeves', 'flexible stretcher', 'stokes', 'device'],
      },
      {
        id: 'emergency-moves',
        title: 'Emergency, urgent, and non-urgent moves',
        summary: 'Three tiers, and picking the wrong one is a decision you will have to defend.',
        points: [
          'Emergency move: immediate danger — fire, explosion, unsecurable scene — or you cannot reach a second, more critical patient. Accept the spinal risk; drag along the long axis of the body.',
          'Urgent move: the patient’s condition demands it, as with a rapid extrication from a vehicle for a deteriorating patient.',
          'Non-urgent move: no time pressure. Package properly, and use the device the route calls for.',
          'Drags — shoulder, blanket, ankle, clothing — keep the head and spine in line as best you can and get the patient out.',
          'Say which tier you are in out loud, so the whole crew knows why the packaging just got shorter.',
        ],
        keywords: ['emergency move', 'rapid extrication', 'drag', 'urgent move', 'packaging'],
      },
      {
        id: 'stairs',
        title: 'Stairs and confined spaces',
        summary: 'Where BLS-01 lives: a patient, three flights, and the crew you thought to call for.',
        points: [
          'Count the people you need before you start moving, and call for them while you are still assessing. Help requested at the top of the stairs arrives after you needed it.',
          'Head uphill going down stairs — the patient goes feet-first down, with the head elevated.',
          'Post a spotter at every turn and landing, and clear the route: rugs, toys, pets, the chair nobody moved.',
          'Rest at the landing on purpose rather than when someone’s grip fails. Announce the rest before the lift begins.',
          'Consider whether the patient can walk with assistance. Sometimes the safest extrication is the one where the patient carries themselves.',
        ],
        keywords: ['stairs', 'staircase', 'landing', 'second floor', 'no elevator', 'confined space', 'carry'],
      },
    ],
  },
  {
    id: 'communication',
    title: 'Communication and documentation',
    purpose: 'The parts of the call that outlive the call.',
    entries: [
      {
        id: 'radio-report',
        title: 'Radio report',
        summary: 'Short, ordered, and predictable. The receiving facility needs to build a picture, not follow a story.',
        points: [
          'Unit, level of service, and estimated time of arrival first.',
          'Age, sex, chief complaint, and the mechanism or nature of the call.',
          'Pertinent findings, vital signs, and mental status.',
          'What you have done, and how the patient responded to it.',
          'Your request: a trauma alert, a STEMI activation, a stroke alert, or the room you need.',
          'Keep it under about 30 seconds. Details belong in the handoff at the bedside.',
        ],
        keywords: ['radio', 'report', 'patch', 'hospital notification', 'eta', 'alert'],
      },
      {
        id: 'handoff',
        title: 'Bedside handoff',
        summary: 'The single highest-risk moment for information loss on the whole call.',
        points: [
          'MIST for trauma — Mechanism, Injuries found, Signs and vitals, Treatment given.',
          'SBAR for medical — Situation, Background, Assessment, Recommendation.',
          'Give it once, to the person taking the patient, with the room quiet enough to hear you.',
          'Hand over what you saw that the hospital cannot see: the scene, the pill bottles, the family’s account, the position you found them in.',
          'Do not leave until the receiving clinician has acknowledged the handoff.',
        ],
        keywords: ['handoff', 'handover', 'sbar', 'mist', 'transfer of care', 'bedside'],
      },
      {
        id: 'documentation',
        title: 'Documentation',
        summary: 'If it is not in the report, it is very hard to argue that it happened.',
        points: [
          'Document what you found, what you did, and the time you did it. Times are what make a narrative defensible.',
          'Record pertinent negatives — what you looked for and did not find is clinical information.',
          'Quote the patient for the chief complaint and for any refusal. Their words, in quotation marks.',
          'Correct an error with a single strike-through, an initial, and the correction. Never obliterate or backdate.',
          'Objective before subjective: describe the finding, and let the impression follow from it.',
        ],
        keywords: ['pcr', 'charting', 'narrative', 'report writing', 'documentation', 'legal'],
      },
      {
        id: 'refusal',
        title: 'Refusal of care',
        summary: 'The highest-liability call you will run, and the one with no patient to point at afterwards.',
        points: [
          'Capacity requires an adult who is alert and oriented, not intoxicated or head-injured, and who can repeat back the risks in their own words.',
          'Assess and document the refusal like any other call: vitals, a glucose where relevant, and a mental-status finding.',
          'Explain the specific risks including death, offer transport again, and document that you offered.',
          'Get the signature, and a witness signature — a police officer or family member — where you can.',
          'Tell them to call back, and mean it. Document that you said it.',
        ],
        keywords: ['refusal', 'ama', 'against medical advice', 'capacity', 'consent', 'signature'],
      },
    ],
  },
];
