import type { Medication } from './types';

/**
 * Paramedic formulary — the drug cards.
 *
 * Doses here are the widely-taught typical adult/pediatric values used for
 * training recall. They are NOT a protocol: the UI renders
 * PROTOCOL_DISCLAIMER above this section, and local medical direction governs.
 * Kept in its own module so the formulary can grow without touching the prose
 * chapters, and so the search index can weight it separately.
 */

/** The chapter id the formulary is presented under, for search breadcrumbs. */
export const FORMULARY_CHAPTER_ID = 'formulary';
export const FORMULARY_CHAPTER_TITLE = 'Formulary';

export const MEDICATIONS: readonly Medication[] = [
  {
    id: 'med-epinephrine',
    name: 'Epinephrine',
    alsoKnownAs: 'Adrenaline',
    drugClass: 'Sympathomimetic — alpha and beta agonist',
    indications: ['Cardiac arrest', 'Anaphylaxis', 'Severe asthma', 'Symptomatic bradycardia (infusion)'],
    adultDose:
      'Arrest: 1 mg (10 mL of 0.1 mg/mL) IV/IO every 3–5 min. Anaphylaxis: 0.3–0.5 mg (1 mg/mL) IM into the lateral thigh, repeat every 5–15 min as needed.',
    pediatricDose:
      'Arrest: 0.01 mg/kg (0.1 mL/kg of 0.1 mg/mL) IV/IO every 3–5 min. Anaphylaxis: 0.01 mg/kg (1 mg/mL) IM, max 0.3 mg.',
    contraindications: ['No absolute contraindication in cardiac arrest or anaphylaxis'],
    cautions: [
      'Two concentrations exist and they are not interchangeable — 1 mg/mL is the IM anaphylaxis concentration, 0.1 mg/mL is the IV arrest concentration. Read the vial out loud.',
      'Increases myocardial oxygen demand; use care in known coronary disease.',
      'Tachycardia, hypertension, anxiety, and tremor are expected effects.',
    ],
    keywords: ['epi', 'adrenaline', 'anaphylaxis', 'arrest', 'code', 'epipen'],
  },
  {
    id: 'med-amiodarone',
    name: 'Amiodarone',
    alsoKnownAs: 'Cordarone',
    drugClass: 'Class III antiarrhythmic',
    indications: ['VF or pulseless VT refractory to defibrillation', 'Stable wide-complex tachycardia'],
    adultDose: 'Arrest: 300 mg IV/IO push, then 150 mg for a repeat dose. With a pulse: 150 mg over 10 min.',
    pediatricDose: 'Arrest: 5 mg/kg IV/IO, may repeat to a total of 15 mg/kg.',
    contraindications: ['Known hypersensitivity', 'Second- or third-degree block without a pacemaker', 'Cardiogenic shock'],
    cautions: ['Hypotension and bradycardia, particularly when pushed fast in a patient with a pulse.'],
    keywords: ['cordarone', 'antiarrhythmic', 'vfib', 'vtach', 'refractory'],
  },
  {
    id: 'med-adenosine',
    name: 'Adenosine',
    alsoKnownAs: 'Adenocard',
    drugClass: 'Antiarrhythmic — AV nodal blocking agent',
    indications: ['Stable narrow-complex regular SVT unresponsive to vagal maneuvers'],
    adultDose: '6 mg rapid IV push followed immediately by a 20 mL flush and arm elevation; then 12 mg if needed.',
    pediatricDose: '0.1 mg/kg rapid IV/IO (max 6 mg), then 0.2 mg/kg (max 12 mg).',
    contraindications: ['Second- or third-degree block', 'Sick sinus syndrome without a pacemaker', 'Known bronchospasm from prior dose'],
    cautions: [
      'Half-life is seconds — it must go in fast, through a proximal line, with an immediate flush.',
      'Warn the patient: a brief asystolic pause, flushing, and chest discomfort are expected and frightening.',
      'Record a rhythm strip through the administration; the conversion is the diagnosis.',
    ],
    keywords: ['adenocard', 'svt', 'push', 'flush', 'narrow complex'],
  },
  {
    id: 'med-atropine',
    name: 'Atropine sulfate',
    drugClass: 'Anticholinergic — antimuscarinic',
    indications: ['Symptomatic bradycardia', 'Organophosphate or nerve-agent poisoning'],
    adultDose: 'Bradycardia: 1 mg IV/IO every 3–5 min, maximum total 3 mg. Organophosphate: large repeated doses titrated to drying of secretions.',
    pediatricDose: '0.02 mg/kg IV/IO, minimum single dose 0.1 mg.',
    contraindications: ['No absolute contraindication in symptomatic bradycardia'],
    cautions: [
      'Generally ineffective in high-degree (Mobitz II or third-degree) block — move to pacing rather than repeating doses.',
      'Dry mouth, blurred vision, urinary retention, and confusion in the elderly.',
    ],
    keywords: ['bradycardia', 'anticholinergic', 'organophosphate', 'nerve agent'],
  },
  {
    id: 'med-naloxone',
    name: 'Naloxone',
    alsoKnownAs: 'Narcan',
    drugClass: 'Opioid antagonist',
    indications: ['Respiratory depression from suspected opioid overdose'],
    adultDose: '0.4–2 mg IV/IO/IM, or 2–4 mg intranasal, repeated and titrated to adequate respirations.',
    pediatricDose: '0.1 mg/kg IV/IO/IM/IN, maximum 2 mg per dose.',
    contraindications: ['Known hypersensitivity'],
    cautions: [
      'Ventilate first. Naloxone treats the respiratory drive, but the bag treats the hypoxia now.',
      'Titrate to breathing, not to alertness — a fully-reversed patient may become agitated and refuse care.',
      'It wears off before many opioids do. Re-sedation is a real risk and a reason to transport.',
    ],
    keywords: ['narcan', 'opioid', 'overdose', 'od', 'heroin', 'fentanyl', 'intranasal'],
  },
  {
    id: 'med-dextrose',
    name: 'Dextrose',
    drugClass: 'Carbohydrate — hyperglycemic agent',
    indications: ['Symptomatic hypoglycemia', 'Altered mental status with a low measured glucose'],
    adultDose: '10–25 g IV (e.g. 100–250 mL of D10, or 25 g of D50), re-checking glucose after administration.',
    pediatricDose: 'D10 at 5 mL/kg IV/IO; neonates typically D10 at 2 mL/kg.',
    contraindications: ['Do not give without a measured glucose where one can be obtained'],
    cautions: [
      'Confirm a patent IV — extravasated concentrated dextrose causes tissue necrosis.',
      'Recheck the glucose after treatment, and again before accepting any refusal.',
    ],
    keywords: ['d50', 'd10', 'glucose', 'sugar', 'hypoglycemia', 'amp'],
  },
  {
    id: 'med-glucagon',
    name: 'Glucagon',
    drugClass: 'Pancreatic hormone',
    indications: ['Hypoglycemia where no IV access is available', 'Beta-blocker overdose'],
    adultDose: 'Hypoglycemia: 1 mg IM/IN/SubQ. Beta-blocker overdose: larger doses per protocol.',
    pediatricDose: '0.5 mg IM for a patient under about 20 kg; 1 mg above.',
    contraindications: ['Known hypersensitivity', 'Pheochromocytoma'],
    cautions: [
      'Slow onset — expect several minutes, and it needs adequate liver glycogen to work at all.',
      'Nausea and vomiting are common; be ready to protect the airway.',
    ],
    keywords: ['hypoglycemia', 'no iv', 'im', 'beta blocker'],
  },
  {
    id: 'med-albuterol',
    name: 'Albuterol',
    alsoKnownAs: 'Salbutamol / Ventolin',
    drugClass: 'Beta-2 agonist bronchodilator',
    indications: ['Bronchospasm from asthma, COPD, or anaphylaxis', 'Hyperkalemia (adjunct)'],
    adultDose: '2.5 mg nebulized, repeated or given continuously as needed.',
    pediatricDose: '2.5 mg nebulized (some systems use 1.25 mg for infants).',
    contraindications: ['Known hypersensitivity'],
    cautions: ['Tachycardia, tremor, and palpitations. Use care in known coronary disease and in tachydysrhythmias.'],
    keywords: ['ventolin', 'salbutamol', 'neb', 'nebulizer', 'asthma', 'copd', 'wheeze'],
  },
  {
    id: 'med-ipratropium',
    name: 'Ipratropium bromide',
    alsoKnownAs: 'Atrovent',
    drugClass: 'Anticholinergic bronchodilator',
    indications: ['Bronchospasm, given with albuterol'],
    adultDose: '0.5 mg nebulized, usually combined with albuterol as a single treatment.',
    pediatricDose: '0.25–0.5 mg nebulized per protocol.',
    contraindications: ['Known hypersensitivity, including to soy or peanut in some formulations'],
    cautions: ['Shield the eyes — the mist can precipitate acute angle-closure glaucoma in susceptible patients.'],
    keywords: ['atrovent', 'duoneb', 'neb', 'combination'],
  },
  {
    id: 'med-nitroglycerin',
    name: 'Nitroglycerin',
    alsoKnownAs: 'NTG / Nitro',
    drugClass: 'Nitrate vasodilator',
    indications: ['Ischemic chest pain', 'Acute pulmonary edema / congestive heart failure'],
    adultDose: '0.4 mg sublingual every 5 min, up to 3 doses, reassessing blood pressure before each.',
    contraindications: [
      'Systolic blood pressure below about 100 mmHg',
      'Phosphodiesterase-5 inhibitor (sildenafil, tadalafil, vardenafil) within 24–48 hours',
      'Suspected right ventricular infarct',
      'Marked bradycardia or tachycardia',
    ],
    cautions: [
      'Take a blood pressure before EVERY dose, not just the first.',
      'Establish IV access first where practical — the pressure can drop precipitously.',
      'Headache and hypotension are the expected effects.',
    ],
    keywords: ['ntg', 'nitro', 'chest pain', 'viagra', 'sildenafil', 'sublingual', 'spray'],
  },
  {
    id: 'med-aspirin',
    name: 'Aspirin',
    alsoKnownAs: 'ASA',
    drugClass: 'Antiplatelet / salicylate',
    indications: ['Suspected acute coronary syndrome'],
    adultDose: '162–324 mg chewed (typically four 81 mg chewable tablets).',
    contraindications: ['Known aspirin allergy', 'Active gastrointestinal bleeding', 'Inability to swallow or protect the airway'],
    cautions: ['It must be chewed, not swallowed whole. Ask specifically about an aspirin allergy, not "any allergies".'],
    keywords: ['asa', 'aspirin', 'acs', 'mi', 'chest pain', 'chewable', 'antiplatelet'],
  },
  {
    id: 'med-fentanyl',
    name: 'Fentanyl',
    drugClass: 'Synthetic opioid analgesic',
    indications: ['Moderate to severe pain', 'Analgesia for painful procedures'],
    adultDose: '1 mcg/kg IV/IO/IM (commonly 50–100 mcg), titrated; intranasal dosing per protocol.',
    pediatricDose: '1 mcg/kg IV/IO/IN, titrated to effect.',
    contraindications: ['Hypotension', 'Respiratory depression', 'Known hypersensitivity'],
    cautions: [
      'Monitor respirations and capnography continuously; have naloxone and a BVM at hand before you push.',
      'Chest-wall rigidity is a rare effect of rapid administration.',
      'Reassess and document the pain score after every dose.',
    ],
    keywords: ['pain', 'analgesia', 'opioid', 'narcotic', 'intranasal'],
  },
  {
    id: 'med-morphine',
    name: 'Morphine sulfate',
    drugClass: 'Opioid analgesic',
    indications: ['Moderate to severe pain'],
    adultDose: '2–4 mg IV/IO slowly, repeated and titrated to effect per protocol.',
    pediatricDose: '0.1 mg/kg IV/IO, maximum 4 mg per dose.',
    contraindications: ['Hypotension', 'Respiratory depression', 'Known hypersensitivity', 'Head injury with altered mental status'],
    cautions: ['Histamine release causes vasodilation and hypotension. Slower push, and watch the pressure.'],
    keywords: ['pain', 'analgesia', 'opioid', 'narcotic', 'ms'],
  },
  {
    id: 'med-midazolam',
    name: 'Midazolam',
    alsoKnownAs: 'Versed',
    drugClass: 'Benzodiazepine',
    indications: ['Status epilepticus', 'Sedation for cardioversion or pacing', 'Severe agitation'],
    adultDose: 'Seizure: 10 mg IM, or 2.5–5 mg IV/IO/IN titrated. Sedation: 2.5–5 mg IV titrated.',
    pediatricDose: '0.1–0.2 mg/kg IM/IN, or 0.1 mg/kg IV/IO per protocol.',
    contraindications: ['Known hypersensitivity', 'Hypotension', 'Acute narrow-angle glaucoma'],
    cautions: [
      'Respiratory depression and hypotension — have airway equipment open before the first dose.',
      'Intramuscular is a legitimate first route in an actively seizing patient; do not delay treatment hunting for a vein.',
    ],
    keywords: ['versed', 'benzo', 'seizure', 'sedation', 'status', 'agitation'],
  },
  {
    id: 'med-ondansetron',
    name: 'Ondansetron',
    alsoKnownAs: 'Zofran',
    drugClass: 'Serotonin 5-HT3 antagonist antiemetic',
    indications: ['Nausea and vomiting'],
    adultDose: '4 mg IV/IM, or 4 mg orally disintegrating tablet.',
    pediatricDose: '0.1 mg/kg IV, maximum 4 mg.',
    contraindications: ['Known hypersensitivity', 'Congenital long QT syndrome'],
    cautions: ['QT prolongation — a consideration in patients already on QT-prolonging medication.'],
    keywords: ['zofran', 'nausea', 'vomiting', 'antiemetic', 'odt'],
  },
  {
    id: 'med-diphenhydramine',
    name: 'Diphenhydramine',
    alsoKnownAs: 'Benadryl',
    drugClass: 'H1 antihistamine',
    indications: ['Allergic reaction and anaphylaxis (adjunct to epinephrine)', 'Dystonic reaction'],
    adultDose: '25–50 mg IV/IM.',
    pediatricDose: '1 mg/kg IV/IM, maximum 50 mg.',
    contraindications: ['Known hypersensitivity', 'Neonates'],
    cautions: [
      'It is an adjunct in anaphylaxis, never the treatment — epinephrine comes first and does not wait for it.',
      'Sedation and anticholinergic effects, particularly in the elderly.',
    ],
    keywords: ['benadryl', 'antihistamine', 'allergic', 'allergy', 'hives', 'dystonic'],
  },
  {
    id: 'med-calcium-chloride',
    name: 'Calcium chloride',
    drugClass: 'Electrolyte',
    indications: ['Hyperkalemia with ECG changes', 'Calcium channel blocker overdose', 'Hypocalcemia', 'Hypermagnesemia'],
    adultDose: '1 g (10 mL of 10%) IV/IO slowly.',
    pediatricDose: '20 mg/kg IV/IO per protocol.',
    contraindications: ['Digoxin toxicity (relative — per protocol)', 'Hypercalcemia'],
    cautions: [
      'Never in the same line as sodium bicarbonate without a thorough flush — they precipitate.',
      'Severely tissue-toxic if it extravasates. Confirm the line.',
    ],
    keywords: ['hyperkalemia', 'calcium', 'ccb', 'crush injury', 'electrolyte'],
  },
  {
    id: 'med-sodium-bicarbonate',
    name: 'Sodium bicarbonate',
    drugClass: 'Alkalinizing agent',
    indications: ['Tricyclic antidepressant overdose with a wide QRS', 'Hyperkalemia', 'Severe metabolic acidosis', 'Crush syndrome'],
    adultDose: '1 mEq/kg IV/IO (commonly 50 mEq), repeated per protocol.',
    pediatricDose: '1 mEq/kg IV/IO, diluted for neonates.',
    contraindications: ['Not routine in cardiac arrest — give it for an identified indication'],
    cautions: ['Flush thoroughly between drugs; it inactivates catecholamines and precipitates with calcium.'],
    keywords: ['bicarb', 'tca', 'hyperkalemia', 'acidosis', 'crush', 'wide qrs'],
  },
  {
    id: 'med-magnesium',
    name: 'Magnesium sulfate',
    drugClass: 'Electrolyte / anticonvulsant',
    indications: ['Torsades de pointes', 'Eclampsia', 'Severe refractory asthma'],
    adultDose: 'Torsades: 1–2 g IV/IO. Eclampsia: 4 g IV over several minutes. Asthma: 2 g IV over about 20 min.',
    pediatricDose: '25–50 mg/kg IV/IO, maximum 2 g.',
    contraindications: ['Known hypersensitivity', 'Heart block'],
    cautions: [
      'Hypotension with rapid administration; monitor deep tendon reflexes and respirations in eclampsia dosing.',
      'Calcium is the antidote for magnesium toxicity.',
    ],
    keywords: ['mag', 'torsades', 'eclampsia', 'asthma', 'preeclampsia'],
  },
  {
    id: 'med-oral-glucose',
    name: 'Oral glucose',
    drugClass: 'Carbohydrate',
    indications: ['Hypoglycemia in an alert patient who can protect their own airway'],
    adultDose: '15–25 g of gel or tablets by mouth, repeated after about 15 minutes if the glucose remains low.',
    pediatricDose: 'Per protocol, in a child able to swallow and protect the airway.',
    contraindications: ['Decreased level of consciousness', 'Inability to swallow or protect the airway'],
    cautions: ['Never place gel in the mouth of an unresponsive patient — it is an aspiration route, not a treatment.'],
    keywords: ['glucose gel', 'oral', 'hypoglycemia', 'bls', 'sugar'],
  },
];
